In [4]:
import numpy as np

def run():
    # create a column vector
    col_vec = np.array([[1], [2]])
    print ("column vector")
    print (col_vec)
    print("")
    
    # create a row vector
    row_vec = np.array([[1, 2]])
    print ("row vector")
    print (row_vec)
    print("")
    
    # create a matrix
    mat = np.array([[1, 2], [3, 4]])
    print ("matrix")
    print (mat)
    print("")
    
    # inspect dimensions
    print ("row vector dimensions", row_vec.ndim)
    shape = row_vec.shape
    print ("row vector rows", shape[0], "columns", shape[1])
    print("")
    
    print ("matrix dimensions", mat.ndim)
    shape = mat.shape
    print ("matrix rows", shape[0], "columns", shape[1])
    print("")
    
    # transpose
    vec_t = row_vec.transpose() # or row_vec.T
    print ("transposed vector")
    print (vec_t)
    print("")
    
    mat_t = mat.transpose() # or mat.T
    print ("transposed matrix")
    print (mat_t)
    print("")
    
    a = np.array([[2], [-4], [1]])
    b = np.array([[2], [1], [-2]])
    
    # addition 
    print ("a + b")
    print (a + b)
    print("")
    
    # subtraction
    print ("a - b")
    print (a - b)
    print("")
    
    # scalar multiplication
    print ("1.2 * a")
    print (1.2 * a)
    print("")
    
    # element wise multiplication
    print ("a * b")
    print (a * b)
    print("")
    
    # vector scalar product
    print ("a . b")
    print (np.dot(a.transpose(), b))
    print("")
    
    # vector cross product
    print ("a x b")
    print (np.cross(a, b, axis=0)) # or np.cross(a.T, b.T).T
    print("")
    
    identity = np.array([[1, 0], [0, 1]])
    
    # matrix vector product
    print ("identity . col_vec")
    print (np.dot(identity, col_vec))
    print("")
    
    # matrix product
    print ("identity . mat")
    print (np.dot(identity, mat))
    print("")
    
    


In [5]:
run()

column vector
[[1]
 [2]]

row vector
[[1 2]]

matrix
[[1 2]
 [3 4]]

row vector dimensions 2
row vector rows 1 columns 2

matrix dimensions 2
matrix rows 2 columns 2

transposed vector
[[1]
 [2]]

transposed matrix
[[1 3]
 [2 4]]

a + b
[[ 4]
 [-3]
 [-1]]

a - b
[[ 0]
 [-5]
 [ 3]]

1.2 * a
[[ 2.4]
 [-4.8]
 [ 1.2]]

a * b
[[ 4]
 [-4]
 [-2]]

a . b
[[-2]]

a x b
[[ 7]
 [ 6]
 [10]]

identity . col_vec
[[1]
 [2]]

identity . mat
[[1 2]
 [3 4]]

